INSERT INTO pais(nome) VALUES ('Angola');

INSERT INTO provincia(nome, fk_pais) VALUES ('Luanda', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Bengo', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Benguela', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Bie', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Cabinda', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Cunene', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Kuando-Kubango', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Kwanza-Norte', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Kwanza-Sul', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Huambo', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Huila', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Lunda-Norte', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Lunda-Sul', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Malanje', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Moxico', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Namibe', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Uige', 1);
INSERT INTO provincia(nome, fk_pais) VALUES ('Zaire', 1);

/*Adicionando Municipios*/

INSERT INTO municipio(nome, fk_provincia) VALUES ('Kilamba Kiaxi',1);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Belas',1);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cacuaco',1);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cazenga',1);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Icolo e Bengo',1);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Luanda',1);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Quiçama (Quissama)',1);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Talatona',1);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Viana',1);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Ambriz',2);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Dande',2);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Dembos',2);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Bula Atumba',2);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Nambuangongo',2);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Pango Aluquém (Pango Aluquêm)',2);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Balombo',3);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Baía Farta',3);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Benguela',3);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Bocoio',3);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Caimbambo',3);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Catumbela',3);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Chongoroi',3);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cubal',3);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Ganda',3);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Lobito',3);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Andulo',4);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Camacupa',4);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Catabola',4);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Chinguar',4);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Chitembo',4);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cuemba',4);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cunhinga',4);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cuito (Kuito)',4);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Nharêa',4);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Belize',5);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Buco-Zau',5);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cabinda',5);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cacongo',5);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Cahama',6);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cuanhama (Kwanhama)',6);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Curoca',6);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cuvelai',6);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Namacunde',6);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Ombadja',6);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Bailundo',10);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cachiungo (Catchiungo)',10);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Caála',10);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Ecunha (Ekunha)',10);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Huambo',10);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Londuimbali',10);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Longonjo (Longongo)',10);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Mungo',10);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Chicala-Cholohanga (Tchicala-Tcholoanga)',10);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Chinjenje (Tchindjenje)',10);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Ucuma',10);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Caconda',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cacula',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Caluquembe',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Gambos',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Chibia',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Chicomba',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Chipindo',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Humpata',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Jamba',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cuvango (Kuvango)',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Lubango',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Matala',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Quilengues',11);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Quipungo',11);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Calai',7);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cuangar',7);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cuchi',7);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cuito Cuanavale (Kuito Kuanavale)',7);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Dirico',7);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Nancova (Nankova)',7);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Mavinga',7);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Menongue',7);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Rivungo',7);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Ambaca',8);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Banga',8);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Bolongongo',8);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cambambe',8);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cazengo',8);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Golungo Alto',8);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Ngonguembo (Gonguembo)',8);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Lucala',8);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Quiculungo',8);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Samba Caju',8);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Amboim',9);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cassongue',9);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Conda',9);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Ebo',9);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Libolo',9);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Mussende',9);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Porto Amboim',9);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Quibala',9);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Quilenda',9);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Seles',9);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Sumbe',9);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cela',9);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Cambulo',12);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Capenda Camulemba',12);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Caungula',12);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Chitato',12);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cuango',12);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cuilo',12);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Lubalo',12);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Lucapa',12);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Xá Muteba',12);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Lóvua',12);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Cacolo',13);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Dala',13);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Muconda',13);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Saurimo',13);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Cacuso',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Calandula',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cambundi Catembo',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cangandala',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cahombo (Caombo)',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Kiwaba Nzoji (Cuaba Nzogo)',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Kunda dya Baze (Cunda-Diaza)',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Luquembo',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Malange',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Marimba',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Massango',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Mucari',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Quela',14);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Quirima',14);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Alto Zambeze',15);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Bundas',15);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Camanongue',15);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Cameia (Lumeji)',15);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Luau',15);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Luacano (Lucano)',15);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Luchazes',15);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Léua',15);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Moxico',15);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Bibala',16);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Camacuio (Camulo)',16);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Moçâmedes (Namibe)',16);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Tômbwa',16);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Virei',16);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Alto Cauale',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Ambuíla',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Bembe',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Buengas',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Bungo',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Damba',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Milunga',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Mucaba',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Negage',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Puri',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Quimbele',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Dange-Quitexe',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Pombo',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Songo',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Uíge',17);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Maquela do Zombo',17);

INSERT INTO municipio(nome, fk_provincia) VALUES ('Cuimba',18);
INSERT INTO municipio(nome, fk_provincia) VALUES ('MBanza Kongo',18);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Noqui',18);
INSERT INTO municipio(nome, fk_provincia) VALUES ('NZeto',18);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Soyo',18);
INSERT INTO municipio(nome, fk_provincia) VALUES ('Tomboco',18);

/*Adicionando comunas*/

INSERT INTO comuna(nome, fk_municipio) VALUES ('Golfe',1);

INSERT INTO comuna(nome, fk_municipio) VALUES ('Palanca',1);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Nova Vida',1);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Sapú',1);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Barra do Kwanza',2);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cabolombo',2);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kilamba',2);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Morro dos Veados',2);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Quenguela',2);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Ramiros',2);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Vila Verde',2);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cacuaco',3);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Funda',3);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kikolo',3);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mulenvos de Baixo',3);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Sequele',3);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cazenga Popular',4);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Hoji-ya-Henda',4);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kalawenda',4);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kima Kieza',4);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Tala Hadi',4);
INSERT INTO comuna(nome, fk_municipio) VALUES ('11 de Novembro',4);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Bela Vista',5);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Bom Jesus',5);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cabiri',5);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Catete',5);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cassoneca',5);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Caculo Cahango',5);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cabo Ledo',7);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Demba-Chio',7);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mumbondo',7);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Muxima',7);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Quixingue',7);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Benfica',8);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Camama',8);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cidade Universitária',8);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Futungo de Belas',8);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Lar do Patriota',8);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mussulo',8);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Talatona',8);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Calumbo',9);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Viana',9);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kikuxi',9);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Ambriz',10);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Bela Vista',10);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Tabi',10);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Bula Atumba',13);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Quiage',13);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Barra do Dande',11);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Caxito',11);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mabubas',11);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Quicabo',11);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Úcua',11);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Paredes',12);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Piri',12);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Quixabe',12);
INSERT INTO comuna(nome, fk_municipio) VALUES ('São José das Matas',12);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cage',14);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Canacassala',14);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Gombe',14);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Muxaluando',14);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Quicunzo',14);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Quixico',14);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Zala',14);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Pango-Aluquém',15);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cazuangongo',15);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Baía Farta',17);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Dombe Grande',17);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Esquimina',17);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kalohanga',17);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Balombo',16);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chindumbo',16);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chingongo',16);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Maka-Mombolo',16);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Bocoio',19);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chila',19);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cubal do Lumbo',19);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Monte Belo',19);

INSERT INTO comuna(nome, fk_municipio) VALUES ('Passe',19);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Caimbambo',20);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Canhamela',20);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Catengue',20);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cayavi',20);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Wyangombe',20);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Biopia',21);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Catumbela',21);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Gama',21);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Egito Praia',21);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Bolonguera',22);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chongorói',22);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kamuine',22);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Capupa',23);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cubal',23);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Imbala',23);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Tumbulo',23);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Babaera',24);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Casseque',24);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chicuma',24);

INSERT INTO comuna(nome, fk_municipio) VALUES ('Ebanga',24);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Ganda',24);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Lobito',25);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Canjala',25);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Culango',25);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Andulo',26);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Calucinga',26);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cassumbe',26);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chivaúlo',26);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Camacupa',27);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cuanza',27);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Ringoma',27);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Santo António de Muinha',27);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Umpulo',27);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Caivera',28);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Catabola',28);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chipeta',28);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chiuca',28);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Sande',28);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chinguar',29);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cutato',29);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kangote',29);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cachingues',30);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chitembo',30);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Malengue',30);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mutambo',30);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mumbué',30);

INSERT INTO comuna(nome, fk_municipio) VALUES ('Soma Cuanza',30);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cuemba',31);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Luando',31);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Sachineuma',31);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Belo Horizonte',32);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cunhinga',32);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chicala',33);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kambândua',33);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kuito',33);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kunje',33);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Trumba',33);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Caieie',34);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Dando',34);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Gamba',34);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Lúbia',34);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Nharea',34);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Belize',35);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Luali',35);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Miconje',35);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cabinda',37);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Malembo',37);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Tanto-Zinze',37);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Buco-Zau',36);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Inhuca',36);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Necuto',36);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Dinge',38);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Lândana',38);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Massabi',38);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Calai',70);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Maúe',70);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mavengue',70);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Bondo',71);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cuangar',71);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Savate',71);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chinguanja',72);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cuchi',72);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cutato',72);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Muila',72);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Baixo Longa',73);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cuito Cuanavale',73);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Longa',73);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Lupire',73);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Dirico',74);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mucusso',74);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Xamavera',74);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cunjamba',76);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cutuile',76);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Luengue',76);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mavinga',76);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Caiundo',77);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cueio',77);

INSERT INTO comuna(nome, fk_municipio) VALUES ('Menongue',77);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Caála',75);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Rito',75);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chipundo/Neriquinha',78);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Luiana',78);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Rivungo',78);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cahama',39);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Otchindjau',39);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chimpolo',40);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Evale',40);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Môngua',40);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Nehone',40);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Ondjiva',40);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chitado',41);

INSERT INTO comuna(nome, fk_municipio) VALUES ('Oncócua',41);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kalonga',42);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kubati',42);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mukolongondjo',42);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mupa',42);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Namacunde',43);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Shiede',43);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Humbe',44);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mucope',44);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Naulila',44);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Ombala-yo-Mungo',44);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Xangongo',44);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chipipa',49);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kalima',49);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Huambo',49);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Bailundo',45);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Binge',45);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Henge',45);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Lunge',45);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Luvemba',45);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Ekunha',48);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Tchipeio',48);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Caála',47);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kalenga',47);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Katata',47);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kuima',47);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Catchiungo',46);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chinhama',46);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chiumo',46);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Alto Uama',50);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Galanga',50);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kumbila',50);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Londuimbale',50);


INSERT INTO comuna(nome, fk_municipio) VALUES ('Ussoke',50);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chilata',51);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Katabola',51);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Lepi',51);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kambuengo',52);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mungo',52);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mbave',53);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Sambo',53);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Samboto',53);

INSERT INTO comuna(nome, fk_municipio) VALUES ('Tchicala-Tcholonga',53);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chiaca',54);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Tchindjenje',54);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Kakoma',55);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mundundo',55);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Ucama',55);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Caconda',56);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cusse',56);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Gungi',56);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Uaba',56);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cacula',57);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Caluquembe',58);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chiange',1);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chibemba',1);

INSERT INTO comuna(nome, fk_municipio) VALUES ('Capunda',60);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cavilongo',60);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chibia',60);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Jau',60);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Quihita',60);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chicomba',61);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cutenda',61);

INSERT INTO comuna(nome, fk_municipio) VALUES ('Libongue',61);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Quê',61);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Bambi',62);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Chipindo',62);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cuvango',65);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Galangue',65);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Vicungo',65);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Humpata',63);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Cassinga',64);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Dongo',64);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Jamba',64);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Arimba',66);

INSERT INTO comuna(nome, fk_municipio) VALUES ('Hoque',66);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Huíla',66);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Lubango',66);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Capelongo',67);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Matala',67);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Mulongo',67);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Dinde',68);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Impulso',68);

INSERT INTO comuna(nome, fk_municipio) VALUES ('Quilengues',68);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Quipungo',69);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Ambaca',79);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Bindo',79);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Luinga',79);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Maua',79);
INSERT INTO comuna(nome, fk_municipio) VALUES ('Tango',79);

/*Parei na linha 280 em comunas*/
